#指定基底文件為jupyter/base-notebook
FROM yangty10/news_jupyter-tutorial
#安裝flask 0.12, request, line-bot-sdk
RUN pip install --upgrade pip
RUN pip install Flask==0.12 line-bot-sdk
RUN pip install bs4 requests redis python-logstash kafka schedule
RUN pip install udicOpenData Swinger pandas networkx textrank4zh elasticsearch gensim
ADD ./dict_all.txt /opt/conda/lib/python3.6/site-packages/udicOpenData/dictionary/
